---
- name: Create a user and add permissions
  hosts: all
  become: yes
  tasks:
  - name: create user
    user: 
      name: nfsuser
      state: present
      groups: wheel
      append: yes
    when: '"node2" in inventory_hostname'
    register: creat

  - debug:
      var: creat

  - name: Set up authorized keys for the deployer user
    authorized_key: 
      user: nfsuser 
      key: "{{item}}"
    with_file:
    - /home/vagrant/.ssh/id_rsa.pub
    when: '"node2" in inventory_hostname'

  
  - name: Allow 'wheel' group to have passwordless sudo
    lineinfile:
      dest: /etc/sudoers
      state: present
      regexp: '^%wheel'
      line: '%wheel ALL=(ALL) NOPASSWD: ALL'
      validate: 'visudo -cf %s'
